### PR TITLE
Module 5 FanPage Pt3 

### PR DESCRIPTION
**Pull request by andrewmdav**

### CODE REVIEW

**Comment by mbMosman** [comment]
Looks good!

**Comment by andrewmdav** [comment]
Hi Mary,
Something that's bothered me for a few weeks is the row of pictures that I have at the bottom of my fan page site.  The one on the right is a background image, so it is what it is.  But the two on the left have been smashed together until this week.  I put a relative position on the second one, but when the browser changes sizes it gets a little crazy.  
Is there a quick way to put the first picture to the left and align the second in a centered position?  Maybe this if for a later module but thought I should ask.
Thanks,Andrew




 

    On Tuesday, February 14, 2017 2:07 PM, Mary Mosman <notifications@github.com> wrote:
 

 Closed #47.—

**Comment by mbMosman** [comment]
Yeah... things do get a little crazy when browser sizes change.  We'll be learning more about how to deal with the browser size changes in Chapter 8 of the textbook, just a little bit further out.  You'll also learn even better ways to manage this as we get into working with Bootstrap for our final project.


For now, don't stress it.  Make it look OK at a pretty typical browser size and don't worry about the others yet.


Mary Mosman

Computer Careers Faculty

Brooklyn Park Campus, 9000 Brooklyn Boulevard, Brooklyn Park, MN 55445

Eden Prairie Campus, 13100 College View Drive, Eden Prairie, MN 55347

HennepinTech.edu<https://mail.hennepintech.edu/owa/redir.aspx?SURL=X9_UXdraVORHgBEDAbJjlW7lFDPLHRjN-BS9r4ndo2C1J6JJO7nSCGgAdAB0AHAAcwA6AC8ALwBoAGUAbgBuAGUAcABpAG4AdABlAGMAaAAuAGUAZAB1AC8A&URL=https%3a%2f%2fhennepintech.edu%2f>

Support the HTC Foundation by using AmazonSmile<https://mail.hennepintech.edu/owa/redir.aspx?SURL=mTQW3FiySLMvYJeLHK4cUN5xDY1QSOqoOR3YmKzO9qu1J6JJO7nSCGgAdAB0AHAAOgAvAC8AcwBtAGkAbABlAC4AYQBtAGEAegBvAG4ALgBjAG8AbQAvAGMAaAAvADQAMQAtADEAOQA0ADMAMQA0ADkA&URL=http%3a%2f%2fsmile.amazon.com%2fch%2f41-1943149>

________________________________

**Comment by andrewmdav** [comment]
Sounds good ! 

    On Tuesday, February 14, 2017 4:39 PM, Mary Mosman <notifications@github.com> wrote:
 

 Yeah... things do get a little crazy when browser sizes change. We'll be learning more about how to deal with the browser size changes in Chapter 8 of the textbook, just a little bit further out. You'll also learn even better ways to manage this as we get into working with Bootstrap for our final project.


For now, don't stress it. Make it look OK at a pretty typical browser size and don't worry about the others yet.


Mary Mosman

Computer Careers Faculty

Brooklyn Park Campus, 9000 Brooklyn Boulevard, Brooklyn Park, MN 55445

Eden Prairie Campus, 13100 College View Drive, Eden Prairie, MN 55347

HennepinTech.edu<https://mail.hennepintech.edu/owa/redir.aspx?SURL=X9_UXdraVORHgBEDAbJjlW7lFDPLHRjN-BS9r4ndo2C1J6JJO7nSCGgAdAB0AHAAcwA6AC8ALwBoAGUAbgBuAGUAcABpAG4AdABlAGMAaAAuAGUAZAB1AC8A&URL=https%3a%2f%2fhennepintech.edu%2f>

Support the HTC Foundation by using AmazonSmile<https://mail.hennepintech.edu/owa/redir.aspx?SURL=mTQW3FiySLMvYJeLHK4cUN5xDY1QSOqoOR3YmKzO9qu1J6JJO7nSCGgAdAB0AHAAOgAvAC8AcwBtAGkAbABlAC4AYQBtAGEAegBvAG4ALgBjAG8AbQAvAGMAaAAvADQAMQAtADEAOQA0ADMAMQA0ADkA&URL=http%3a%2f%2fsmile.amazon.com%2fch%2f41-1943149>

________________________________

**Pull request closed without merging**
